version: "3.8"

services:
  python_test:
    build:
      context: ./python-container
    image: test_script_python:v1.0
    container_name: test_script_python
    env_file: 
      - ~/idrac.env
    networks:
      - python_test

networks:
  python_test:
    driver: bridge
